#!/bin/csh
#PBS -l select=32:ncpus=24:model=has
##PBS -l select=39:ncpus=20:model=ivy
##PBS -l walltime=28:00:00
##PBS -q long
#PBS -l walltime=2:00:00
##PBS -q debug
#PBS -q devel
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-sgi
module list

umask 027
cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 767 ./mitgcmuv
