#!/bin/csh
#PBS -l select=6:ncpus=20:model=ivy

##PBS -l walltime=120:00:00
##PBS -q long

#PBS -l walltime=2:00:00
#PBS -q devel
##PBS -q debug

#PBS -j oe
#PBS -m abe

#PBS -N ECCOV4r5
#PBS -o output
#PBS -e error

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 113 ./mitgcmuv
