#!/bin/csh
#PBS -l select=20:ncpus=40:model=sky_ele
#PBS -W group_list=g26113

##PBS -q long
##PBS -l walltime=120:00:00

#PBS -q debug
#PBS -l walltime=2:00:00

#PBS -j oe
#PBS -m abe
#PBS -N LLC270_OAE

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 022
cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 767 ./mitgcmuv
