#!/bin/bash

# from: "linux_ia64_pgf77+mpi_cray_xt3_jaguar" file

#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia64_pgf77+mpi_cray_xt3_jaguar,v 1.1 2008/04/16 20:19:04 heimbach Exp $
# heimbach@mit.edu, ce107@mit.edu
# tested on jaguarcnl.ccs.ornl.gov CRAY XT3

CPP='cpp -traditional -P'
FC='ftn'

MPIFC='ftn'
MPILD='ftn'

CC='cc'
##### DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXT'
#XXX CPPDEFS='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXC'
#XXX CPPFLAGS='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXC'
#DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXC'
DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXT'

###INCLUDES='-I/usr/local/mpich-1.2.1/pgi_fortran_binding/include'
##### LIBS='-lfmpich -lmpich'

LIBS='-lfmpich -lmpich'

INCLUDES="-I${MPICH_DIR}/include"

#####    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
#####    FOPTIM='-tp k8-64 -pc=64 -fastsse -O3 -Msmart'

#####    FFLAGS='-byteswapio -Mnodclchk -Mextend'
#####    FOPTIM='-pc=64 -fastsse -O3 -Msmart'
    FFLAGS='-hbyteswapio'
    FOPTIM='-O3'
# -Mvect=cachesize:512000,transform

#    LDFLAGS=
