#!/bin/csh
#PBS -l select=80:ncpus=28:model=bro
#PBS -l walltime=148:00:00
##PBS -l walltime=48:00:00
#PBS -q vlong
##PBS -l walltime=2:00:00
##PBS -q devel
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-sgi hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 027
cd $PBS_O_WORKDIR
limit stacksize unlimited
#./modpickup
#mpiexec -np 577 ./mitgcmuv
mpiexec -np 2227 ./mitgcmuv

