#!/bin/csh
#PBS -l select=6:ncpus=20:model=ivy

##PBS -l walltime=120:00:00
##PBS -q long

#PBS -l walltime=2:00:00
#PBS -q devel
##PBS -q debug

#PBS -j oe
#PBS -m abe

#PBS -N ECCOV4r5
#PBS -o output
#PBS -e error

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

cd $PBS_O_WORKDIR
limit stacksize unlimited

set INPUTDIR = /nobackup/hzhang1/pub/Release5
ln -s ${INPUTDIR}/input_bin/* .
ln -s ${INPUTDIR}/input_forcing/* .
mpiexec -np 113 ./mitgcmuv

#above for 1992/01/01 -- 2020/01/01
#below for 2020/01/01 -- on
ln -s ${INPUTDIR}/input_forcing_ext/* .
mv data_ext      data
mv data.ctrl_ext data.ctrl
mv data.exf_ext  data.exf
mpiexec -np 113 ./mitgcmuv
