#!/bin/csh
#PBS -l select=6:ncpus=20:model=ivy
#below 2 lines for test:
#PBS -l walltime=2:00:00
#PBS -q devel
#below 2 lines for production:
##PBS -l walltime=24:00:00
##PBS -q long
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

cd $PBS_O_WORKDIR
limit stacksize unlimited

set INPUTDIR = /nobackup/hzhang1/pub/Release5
ln -s ${INPUTDIR}/input_bin/* .
mpiexec -np 113 ./mitgcmuv

#above for 1992/01/01 -- 2020/01/01
#below for 2020/01/01 -- on
ln -s ${INPUTDIR}/input_forcing_ext/* .
mv data_ext      data
mv data.exf_ext  data.exf
mpiexec -np 113 ./mitgcmuv

