#!/bin/csh
#PBS -l select=24:ncpus=20:model=ivy
#PBS -l site=needed=/home1+/nobackupp19

##When runing the full configuration
##PBS -l walltime=120:00:00
##PBS -q long
##When runing the 1 step configuration
#PBS -l walltime=2:00:00
#PBS -q debug

#PBS -m abe
#PBS -N downscal
#PBS -o output
#PBS -e error

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 027
cd $PBS_O_WORKDIR
limit stacksize unlimited
setenv MPI_LAUNCH_TIMEOUT 40
mpiexec -np 476 ./mitgcmuv

