#!/bin/csh
#PBS -l select=1:ncpus=16:model=has

#PBS -q normal
#PBS -l walltime=8:00:00

##PBS -l walltime=120:00:00
##PBS -q long

##PBS -l walltime=1:30:00
##PBS -q debug
##PBS -q devel

#PBS -j oe
#PBS -m abe

#PBS -N v05_3deg_CDR
#PBS -o output
#PBS -e error

module purge
module load comp-intel/2020.4.304 mpi-hpe hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 022
cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 16 ./mitgcmuv
