#! /bin/csh
set filesize=3782894400
set last_pickup=`ls -lt pickup.*.data | awk '$5~/'${filesize}'/{print $NF}'|head -1 `
if (-e ${last_pickup}) then
set last_meta=`echo $last_pickup | sed 's/data/meta/'`
set timestep=`awk '$1~/timeStepNumber/{printf("%010d",$4)}' $last_meta`
\ln -sf ${last_pickup} pickup.${timestep}.data
set last_pickupmeta=`echo $last_pickup|awk '{split($0,a,".");print a[1]"."a[2]".meta"}'`
\ln -sf ${last_pickupmeta} pickup.${timestep}.meta
endif

set filesize=162302400
set last_pickup_seaice=`ls -lt pickup_seaice.*.data | awk '$5~/'${filesize}'/{print $NF}'|head -1 `
if (-e ${last_pickup_seaice}) then
set last_meta=`echo $last_pickup_seaice | sed 's/data/meta/'`
set timestep=`awk '$1~/timeStepNumber/{printf("%010d",$4)}' $last_meta`
\ln -sf ${last_pickup_seaice} pickup_seaice.${timestep}.data
set last_pickupmeta=`echo $last_pickup_seaice|awk '{split($0,a,".");print a[1]"."a[2]".meta"}'`
\ln -sf ${last_pickupmeta} pickup_seaice.${timestep}.meta
endif

set filesize=12484800
set last_pickup_dic=`ls -lt pickup_dic.*.data | awk '$5~/'${filesize}'/{print $NF}'|head -1 `
if (-e ${last_pickup_dic}) then
set last_meta=`echo $last_pickup_dic | sed 's/data/meta/'`
set timestep=`awk '$1~/timeStepNumber/{printf("%010d",$4)}' $last_meta`
\ln -sf ${last_pickup_dic} pickup_dic.${timestep}.data
set last_pickupmeta=`echo $last_pickup_dic|awk '{split($0,a,".");print a[1]"."a[2]".meta"}'`
\ln -sf ${last_pickupmeta} pickup_dic.${timestep}.meta
endif

set filesize=24345360000
set last_pickup_ptracers=`ls -lt pickup_ptracers.*.data | awk '$5~/'${filesize}'/{print $NF}'|head -1 `
if (-e ${last_pickup_ptracers}) then
set last_meta=`echo $last_pickup_ptracers | sed 's/data/meta/'`
set timestep=`awk '$1~/timeStepNumber/{printf("%010d",$4)}' $last_meta`
\ln -sf ${last_pickup_ptracers} pickup_ptracers.${timestep}.data
set last_pickupmeta=`echo $last_pickup_ptracers|awk '{split($0,a,".");print a[1]"."a[2]".meta"}'`
\ln -sf ${last_pickupmeta} pickup_ptracers.${timestep}.meta


set newiter0=`expr $timestep \* 1`
ex - data >> /dev/null <<EOF
/niter0=
c
 niter0=${newiter0},
.
w
q
EOF

#\mv data.ptracers data.ptracers.${newiter0}
#\cp data.ptracers.restart data.ptracers
#sed -i s/0000315576/$timestep/g data.ptracers

endif

\mv STDOUT.0000 stdout.${newiter0}
\rm STD*

\rm DIC*.*.meta
\rm ETAN.*.meta
# \rm ETANSQ.*.meta
# \rm EXFhl.*.meta
# \rm EXFhs.*.meta
# \rm EXFlwnet.*.meta
# \rm KPPhbl.*.meta
# \rm KPPmld.*.meta
# \rm PHIBOT.*.meta
# \rm RHOANOSQ.*.meta
# \rm RHOAnoma.*.meta
# \rm SALTSQan.*.meta
\rm SALTanom.*.meta
# \rm SFLUX.*.meta
# \rm SIarea.*.meta
# \rm SIheff.*.meta
# \rm SIhsnow.*.meta
# \rm SIhsalt.*.meta
# \rm SIuice.*.meta
# \rm SIvice.*.meta
# \rm SRELAX.*.meta
# \rm SSS.*.meta
# \rm SST.*.meta
# \rm TFLUX.*.meta
\rm THETA.*.meta
# \rm THETASQ.*.meta
# \rm URHOMASS.*.meta
# \rm USLTMASS.*.meta
# \rm UTHMASS.*.meta
# \rm UVEL.*.meta
# \rm UVELMASS.*.meta
# \rm UVELSQ.*.meta
# \rm UVEL_k2.*.meta
# \rm UV_VEL_Z.*.meta
# \rm VRHOMASS.*.meta
# \rm VSLTMASS.*.meta
# \rm VTHMASS.*.meta
# \rm VVEL.*.meta
# \rm VVELMASS.*.meta
# \rm VVELSQ.*.meta
# \rm VVEL_k2.*.meta
# \rm WRHOMASS.*.meta
# \rm WSLTMASS.*.meta
# \rm WTHMASS.*.meta
# \rm WU_VEL.*.meta
# \rm WVELMASS.*.meta
# \rm WVELSQ.*.meta
# \rm WV_VEL.*.meta
# \rm oceFWflx.*.meta
# \rm oceQnet.*.meta
# \rm oceQsw.*.meta
# \rm oceSflux.*.meta
# \rm oceTAUX.*.meta
# \rm oceTAUY.*.meta
# \rm surForcS.*.meta
# \rm surForcT.*.meta
\rm ALK.*.meta
\rm DIC.*.meta
\rm DICCFLX.*.meta
\rm DICOFLX.*.meta
\rm DICPCO2.*.meta
\rm DICPHAV.*.meta
\rm DICTFLX.*.meta
\rm DOC.*.meta
\rm DOFe.*.meta
\rm DON.*.meta
\rm DOP.*.meta
\rm ETAN.*.meta
\rm FeT.*.meta
\rm NH4.*.meta
\rm NO2.*.meta
\rm NO3.*.meta
\rm O2.*.meta
\rm PIC.*.meta
\rm PO4.*.meta
\rm POC.*.meta
\rm POFe.*.meta
\rm PON.*.meta
\rm POP.*.meta
\rm POSi.*.meta
\rm Phy01.*.meta
\rm Phy02.*.meta
\rm Phy03.*.meta
\rm Phy04.*.meta
\rm Phy05.*.meta
\rm SALTanom.*.meta
\rm SiO2.*.meta
\rm THETA.*.meta
\rm ZOO1Fe.*.meta
\rm ZOO1N.*.meta
\rm ZOO1P.*.meta
\rm ZOO1Si.*.meta
\rm ZOO2Fe.*.meta
\rm ZOO2N.*.meta
\rm ZOO2P.*.meta
\rm ZOO2Si.*.meta
\rm ZOOC1.*.meta
\rm ZOOC2.*.meta
