"""
check_obcs_transport.py

Post-hoc check (and optional correction) of the volume transport carried by
the boundary-normal velocity OBCs that gen_obcs.py already generated,
against the transport actually simulated by the parent (LLC270) model at
the same boundary.

This is intentionally a separate script from gen_obcs.py: it only READS the
OBCS binary files gen_obcs.py already wrote to <config_dir>/forcings/OBCS/,
and it does not modify gen_obcs.py at all -- it just imports a few of its
existing, unmodified grid-reading helpers.

NOTE on a known bug in the ORIGINAL gen_obcs.py (fixed in gen_obcs2.py):
its read_dv_diags() takes an -i iteration list but never actually uses it
to select native diagnostics_vec files -- it globs and reads EVERY
"{bnd}_BC_mask_{vnm}.*" file present in parent/outputs/OBCS/, then a bug in
its merge loop means only the FIRST and LAST file found (by glob order)
survive; anything in between is silently dropped. By default,
read_native_normal_velocity() below reads and correctly concatenates every
available file (matching a fixed generator like gen_obcs2.py). Pass
-legacy-bug-mode to instead replicate the original bug, if you're checking
an OBCS file you know was generated by the unfixed gen_obcs.py.

Workflow:
    1. Run gen_obcs.py as usual to generate forcings/OBCS/*.bin.
    2. Run this script to see the parent-vs-downscaled transport mismatch
       for each open boundary (and optionally a diagnostic plot).
    3. If you want it corrected, pass -correct: a single, per-boundary
       barotropic velocity offset (uniform across depth AND along the whole
       boundary, so both the baroclinic shape and the along-boundary
       spatial pattern gen_obcs.py already produced are left untouched) is
       added to UVEL/VVEL so the boundary's total transport matches the
       parent's, and written to a *separate* output directory (default
       forcings/OBCS_corrected/) alongside untouched copies of the other
       boundary files, so you can point data.obcs at whichever set you
       trust.

Example:
    python3 check_obcs_transport.py -d /path/to/grid -n GoM_1km -bnd ENS \\
                                     -i 26281 -correct -plot -v
"""
import os
import glob
import shutil
import argparse
import warnings
import numpy as np
from MITgcmutils import mds

from gen_obcs import transp_tiles, read_eccogrid, read_ncgrid, read_dv_masks, gen_bnd_domain

NORMAL_VNM = {'east': 'UVEL', 'west': 'UVEL', 'north': 'VVEL', 'south': 'VVEL'}

############################################################
#                      READING FUNCTIONS                   #
############################################################

def read_native_normal_velocity(config_dir, bnd, itrs, bnd_domain, Nr0, verbose=False,
                                 legacy_bug_mode=False):
    """
    Reads the parent's native (diagnostics_vec) UVEL/VVEL at this boundary's
    native points, rotates into true zonal/meridional components (same
    convention gen_obcs.py/gen_obcs2.py use), and returns just the component
    normal to this boundary: zonal for east/west, meridional for north/south.

    Default behavior (matches a FIXED generator, e.g. gen_obcs2.py): every
    available "{bnd}_BC_mask_{vnm}.*" file is read and correctly
    concatenated in chronological (ascending iteration) order.

    Two ways to override:
      - if `itrs` names more than one iteration, it's treated as an
        explicit, authoritative list: exactly those files are read and
        correctly concatenated;
      - pass legacy_bug_mode=True to instead REPLICATE a known bug in the
        original, unfixed gen_obcs.py's read_dv_diags(): it globs every
        file present but a bug in its merge loop means only the FIRST and
        LAST file found (by raw glob order, not chronological) survive --
        everything in between is silently dropped. Use this only when
        checking an OBCS file you know was produced by the original
        gen_obcs.py, so this function's output matches what's actually
        baked into that file.

    Returns: (tstp, Nr0, n0) ndarray.
    """
    dv_dir = os.path.join(config_dir, 'parent/outputs/OBCS/')
    nm_pt = len(bnd_domain[bnd]['XC'])

    def _read_one(itr):
        U = np.fromfile(os.path.join(dv_dir, f"{bnd}_BC_mask_UVEL.{itr:010d}.bin"), '>f4')
        V = np.fromfile(os.path.join(dv_dir, f"{bnd}_BC_mask_VVEL.{itr:010d}.bin"), '>f4')
        tstp_i = U.size // (Nr0 * nm_pt)
        return U.reshape(tstp_i, Nr0, nm_pt), V.reshape(tstp_i, Nr0, nm_pt)

    if len(itrs) > 1:
        if verbose:
            print(f"    [{bnd}] explicit -i list given ({len(itrs)} iteration(s)); reading "
                  f"exactly those files, correctly concatenated")
        U_chunks, V_chunks = [], []
        for itr in sorted(itrs):
            U_i, V_i = _read_one(itr)
            if verbose:
                print(f"        - iteration {itr:010d}: {U_i.shape[0]} timestep(s)")
            U_chunks.append(U_i)
            V_chunks.append(V_i)
        dv_U = np.concatenate(U_chunks, axis=0)
        dv_V = np.concatenate(V_chunks, axis=0)
    elif legacy_bug_mode:
        sfx = os.path.join(dv_dir, "{bnd}_BC_mask_UVEL".format(bnd=bnd))
        found_itrs = [int(p[len(sfx) + 1:-4]) for p in glob.glob(sfx + ".*")]
        if not found_itrs:
            raise SystemExit(f"No {sfx}.*.bin files found -- has diagnostics_vec been run for "
                              f"the '{bnd}' boundary?")
        if verbose:
            print(f"    [{bnd}] --legacy-bug-mode: found {len(found_itrs)} native UVEL/VVEL "
                  f"file(s) (glob order, same as the original gen_obcs.py's read_dv_diags() "
                  f"would see):")

        dv_U_all = dv_V_all = dv_U = dv_V = None
        for i, itr in enumerate(found_itrs):
            U_i, V_i = _read_one(itr)
            if verbose:
                print(f"        - file {i}: iteration {itr:010d}, {U_i.shape[0]} timestep(s)")
            if i == 0:
                dv_U_all, dv_V_all = U_i, V_i
                dv_U, dv_V = U_i, V_i
            else:
                # exact replica of the original gen_obcs.py bug: concatenates
                # [FIRST file] with [this file], never the true running total
                dv_U = np.concatenate([dv_U_all, U_i], axis=0)
                dv_V = np.concatenate([dv_V_all, V_i], axis=0)
        if verbose:
            note = (" (matches file 0 exactly, only one file found)" if len(found_itrs) == 1 else
                    "" if len(found_itrs) == 2 else
                    f" -- files 1..{len(found_itrs)-2} were read then silently discarded by the "
                    f"replicated legacy bug")
            print(f"    [{bnd}] final native array: {dv_U.shape[0]} timestep(s) total{note}")
    else:
        sfx = os.path.join(dv_dir, f"{bnd}_BC_mask_UVEL")
        found_itrs = sorted(int(p[len(sfx) + 1:-4]) for p in glob.glob(sfx + ".*"))
        if not found_itrs:
            raise SystemExit(f"No {sfx}.*.bin files found -- has diagnostics_vec been run for "
                              f"the '{bnd}' boundary?")
        if verbose:
            print(f"    [{bnd}] found {len(found_itrs)} native UVEL/VVEL file(s); reading all, "
                  f"sorted chronologically ascending:")
        U_chunks, V_chunks = [], []
        for itr in found_itrs:
            U_i, V_i = _read_one(itr)
            if verbose:
                print(f"        - iteration {itr:010d}: {U_i.shape[0]} timestep(s)")
            U_chunks.append(U_i)
            V_chunks.append(V_i)
        dv_U = np.concatenate(U_chunks, axis=0)
        dv_V = np.concatenate(V_chunks, axis=0)
        if verbose:
            print(f"    [{bnd}] final native array: {dv_U.shape[0]} timestep(s) total (all "
                  f"{len(found_itrs)} file(s))")

    AngleCS = bnd_domain[bnd]['AngleCS']
    AngleSN = bnd_domain[bnd]['AngleSN']
    if bnd in ('east', 'west'):
        return AngleCS[None, None, :] * dv_U - AngleSN[None, None, :] * dv_V
    else:
        return AngleSN[None, None, :] * dv_U + AngleCS[None, None, :] * dv_V


def read_child_velocity(obcs_dir, bnd, vnm, Nr1, n1):
    """Reads an OBCS binary file gen_obcs.py already wrote. Returns (tstp, Nr1, n1)."""
    path = os.path.join(obcs_dir, f"{vnm}_{bnd}.bin")
    data = np.fromfile(path, '>f4')
    tstp = data.size // (Nr1 * n1)
    return data.reshape(tstp, Nr1, n1)

############################################################
#                    TRANSPORT FUNCTIONS                   #
############################################################

def boundary_transport(vel, mask, drF, face):
    """
    Per-column transport (m^3/s) through a boundary.
        vel:  (..., Nr, n) velocity, normal to the boundary
        mask: (Nr, n) wet fraction (0/1 or hFac)
        drF:  (Nr,) vertical grid spacing
        face: (n,) along-boundary face length (dyG for east/west, dxG for
              north/south)
    Returns an array with the same leading shape as vel, minus the Nr axis.
    """
    return face * np.sum(vel * mask * drF[:, None], axis=-2)


def correct_boundary(bnd, bnd_domain, grid0, native_vel, coord1, face1,
                      child_vel, mask1, drF1, max_correction_speed=2.0,
                      velocity_tolerance=0.2):
    """
    Per-boundary barotropic correction: a SINGLE depth- and space-uniform
    velocity offset, added everywhere this boundary is wet, so the
    boundary's TOTAL transport matches the parent's. Both the baroclinic
    (depth-varying) shape and the along-boundary spatial pattern gen_obcs.py
    already produced are left completely untouched -- only one number per
    timestep is added on top of the existing field.

    The correction is capped two ways, whichever is more restrictive:
      - an absolute cap, +/-max_correction_speed (m/s);
      - a cap derived from the parent's own velocity range at this
        boundary: the correction won't push the field's own min/max beyond
        [parent_min, parent_max] by more than velocity_tolerance (a
        fraction of the parent's speed range, default 0.2 = 20%).

    native_vel: (tstp, Nr0, n0) parent normal velocity, from
        read_native_normal_velocity().
    child_vel: (tstp, Nr1, n1) downscaled normal velocity, from
        read_child_velocity().

    Returns a dict with everything needed to report on / plot the result.
    """
    if bnd in ('east', 'west'):
        coord0 = bnd_domain[bnd]['YC']
        face0 = bnd_domain[bnd]['dyG']
        hFac0 = bnd_domain[bnd]['maskW']
    else:
        coord0 = bnd_domain[bnd]['XC']
        face0 = bnd_domain[bnd]['dxG']
        hFac0 = bnd_domain[bnd]['maskS']
    drF0 = grid0['drF']

    ### Parent (native) transport, summed over the whole boundary, per timestep
    Tp_col = boundary_transport(native_vel, hFac0, drF0, face0)         # (tstp, n0)
    Tp_total = Tp_col.sum(axis=1)                                       # (tstp,)

    ### Downscaled (child) transport before correction, summed over the
    ### whole boundary
    Tc_col_before = boundary_transport(child_vel, mask1, drF1, face1)   # (tstp, n1)
    Tc_total_before = Tc_col_before.sum(axis=1)                         # (tstp,)

    ### Single barotropic correction velocity for the whole boundary
    wet = mask1 > 0
    A_total = float(np.sum(face1 * np.sum(wet * drF1[:, None], axis=0)))   # total wet cross-section, m^2
    dU_raw = np.divide(Tp_total - Tc_total_before, A_total,
                        out=np.zeros_like(Tp_total), where=A_total > 0)    # (tstp,)

    ### Cap 1: absolute limit on the correction itself
    lo_abs, hi_abs = -max_correction_speed, max_correction_speed

    ### Cap 2: don't let the correction push the field's own min/max beyond
    ### the parent's observed range (+/- a tolerance margin)
    parent_min = float(native_vel.min())
    parent_max = float(native_vel.max())
    margin = velocity_tolerance * max(abs(parent_min), abs(parent_max), 0.01)
    range_lo, range_hi = parent_min - margin, parent_max + margin
    child_masked = np.where(wet[None, :, :], child_vel, np.nan)
    with warnings.catch_warnings():
        warnings.simplefilter('ignore', category=RuntimeWarning)   # no wet cells at all -> handled below
        global_min_before = np.nanmin(child_masked, axis=(1, 2))    # (tstp,)
        global_max_before = np.nanmax(child_masked, axis=(1, 2))
    lo_range = range_lo - global_min_before
    hi_range = range_hi - global_max_before
    lo_range = np.where(np.isnan(lo_range), lo_abs, lo_range)
    hi_range = np.where(np.isnan(hi_range), hi_abs, hi_range)

    dU_lo = np.maximum(lo_abs, lo_range)
    dU_hi = np.minimum(hi_abs, hi_range)
    dU_lo = np.minimum(dU_lo, dU_hi)   # guard against the pre-existing (uncorrected)
                                        # field already sitting outside the tolerated
                                        # range -- clip() needs lo<=hi
    dU = np.clip(dU_raw, dU_lo, dU_hi)                                  # (tstp,)

    corrected = child_vel + dU[:, None, None] * wet[None, :, :]
    Tc_col_after = boundary_transport(corrected, mask1, drF1, face1)    # (tstp, n1)
    Tc_total_after = Tc_col_after.sum(axis=1)                           # (tstp,)

    was_clipped = np.abs(dU - dU_raw) > 1e-9
    clipped_frac = float(np.mean(was_clipped))
    wet_len_frac = float(np.sum(face1[np.sum(wet, axis=0) > 0]) / np.sum(face1)) if np.sum(face1) > 0 else 0.0

    corrected_masked = np.where(wet[None, :, :], corrected, np.nan)

    return {
        'corrected': corrected,
        'coord0': coord0, 'coord1': coord1, 'face1': face1,
        'Tp_total': Tp_total, 'Tc_total_before': Tc_total_before, 'Tc_total_after': Tc_total_after,
        'dU': dU, 'dU_raw': dU_raw, 'wet_len_frac': wet_len_frac, 'clipped_frac': clipped_frac,
        'parent_min': parent_min, 'parent_max': parent_max,
        'tolerated_min': range_lo, 'tolerated_max': range_hi,
        'child_min_before': float(np.nanmin(child_masked)) if np.any(wet) else 0.0,
        'child_max_before': float(np.nanmax(child_masked)) if np.any(wet) else 0.0,
        'child_min_after': float(np.nanmin(corrected_masked)) if np.any(wet) else 0.0,
        'child_max_after': float(np.nanmax(corrected_masked)) if np.any(wet) else 0.0,
        # kept for the transect plot: the per-column pattern is unchanged by
        # a bulk correction, so "before" and "after" transects only differ
        # by the constant dU (broadcast, no extra computation needed)
        'q0_col': np.divide(Tp_col, face0, out=np.zeros_like(Tp_col), where=face0 > 0),
        'Tc_col_before': Tc_col_before, 'Tc_col_after': Tc_col_after,
    }

############################################################
#                        REPORTING                         #
############################################################

def print_report(bnd, vnm, result):
    Tp_tot = result['Tp_total'] / 1e6            # Sv, per timestep
    Tcb_tot = result['Tc_total_before'] / 1e6
    Tca_tot = result['Tc_total_after'] / 1e6
    mismatch_before = np.abs(Tp_tot - Tcb_tot)
    mismatch_after = np.abs(Tp_tot - Tca_tot)
    rel_before = mismatch_before.mean() / max(np.abs(Tp_tot).mean(), 1e-6)
    dU_max = np.max(np.abs(result['dU']))

    coord0, coord1 = result['coord0'], result['coord1']
    outside = (coord1 < coord0.min()) | (coord1 > coord0.max())
    frac_outside = float(np.sum(result['face1'][outside]) / np.sum(result['face1']))

    print(f"[{bnd}] {vnm} transport (Sv, {len(Tp_tot)} step(s)):")
    print(f"    parent (native)     : {Tp_tot.mean():8.3f}")
    print(f"    downscaled, before  : {Tcb_tot.mean():8.3f}   (mismatch {mismatch_before.mean():.3f} Sv, "
          f"{rel_before*100:.1f}%)")
    print(f"    downscaled, after   : {Tca_tot.mean():8.3f}   (residual {mismatch_after.mean():.3f} Sv)")
    print(f"    wet length fraction : {result['wet_len_frac']*100:.0f}%   "
          f"barotropic correction: {dU_max*100:.1f} cm/s (uniform across the whole boundary)"
          + (f"   (capped on {result['clipped_frac']*100:.1f}% of timesteps)" if result['clipped_frac'] > 0 else ""))
    print(f"    velocity (m/s)      : parent [{result['parent_min']:.2f}, {result['parent_max']:.2f}]   "
          f"downscaled before [{result['child_min_before']:.2f}, {result['child_max_before']:.2f}]   "
          f"after [{result['child_min_after']:.2f}, {result['child_max_after']:.2f}]")
    # compare against the *tolerated* range (parent range +/- velocity_tolerance),
    # not the raw parent min/max -- the correction is allowed to use that margin,
    # so exceeding parent's raw range alone isn't a problem, only exceeding the
    # tolerated range is
    out_of_range = (result['child_max_after'] > result['tolerated_max'] + 1e-9 or
                     result['child_min_after'] < result['tolerated_min'] - 1e-9)
    if out_of_range:
        print(f"    note: downscaled velocity range after correction still falls outside the parent's "
              f"tolerated range [{result['tolerated_min']:.2f}, {result['tolerated_max']:.2f}] -- this "
              f"usually means the pre-correction (baroclinic) field was already out of range before any "
              f"correction was applied (see the coverage note below if present), since the correction "
              f"itself is capped to not make this worse")
    if frac_outside > 0.05:
        print(f"    note: native samples span [{coord0.min():.2f}, {coord0.max():.2f}], downscaled "
              f"boundary spans [{coord1.min():.2f}, {coord1.max():.2f}] -- {frac_outside*100:.0f}% of the "
              f"boundary length falls outside native coverage (those columns' target is extrapolated from "
              f"the nearest native sample, not independently sampled data; consider regenerating "
              f"'{bnd}_BC_mask.bin' against the current domain if this fraction is large)")

############################################################
#                         PLOTTING                          #
############################################################

def plot_boundary(bnd, vnm, reg_nm, result, plot_dir):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    coord0, coord1, face1 = result['coord0'], result['coord1'], result['face1']
    q0 = result['q0_col']
    q_before = np.divide(result['Tc_col_before'], face1, out=np.zeros_like(result['Tc_col_before']), where=face1 > 0)
    q_after = np.divide(result['Tc_col_after'], face1, out=np.zeros_like(result['Tc_col_after']), where=face1 > 0)
    order0, order1 = np.argsort(coord0), np.argsort(coord1)
    sv_per_100km = 1e5 / 1e6

    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(13, 4.5))

    ax0.plot(coord0[order0], q0.mean(axis=0)[order0] * sv_per_100km, 'o-', ms=3, color='k',
             label='parent (native)')
    ax0.plot(coord1[order1], q_before.mean(axis=0)[order1] * sv_per_100km, '--', color='tab:orange',
             label='downscaled (before)')
    ax0.plot(coord1[order1], q_after.mean(axis=0)[order1] * sv_per_100km, '-', color='tab:green',
             label='downscaled (after = before + uniform shift)')
    ax0.axhline(0, color='gray', lw=0.5)
    ax0.set_xlabel('Latitude' if bnd in ('east', 'west') else 'Longitude')
    ax0.set_ylabel('Transport per unit length (Sv / 100 km)')
    ax0.set_title(f'{reg_nm} {bnd} boundary {vnm}\ntime-mean transect ({q0.shape[0]} step(s))')
    ax0.legend(fontsize=8)

    t_idx = np.arange(result['Tp_total'].shape[0])
    ax1.plot(t_idx, result['Tp_total'] / 1e6, '-', color='k', label='parent')
    ax1.plot(t_idx, result['Tc_total_before'] / 1e6, '--', color='tab:orange', label='downscaled (before)')
    ax1.plot(t_idx, result['Tc_total_after'] / 1e6, '-', color='tab:green', label='downscaled (after)')
    ax1.axhline(0, color='gray', lw=0.5)
    ax1.set_xlabel('Time step')
    ax1.set_ylabel('Net transport (Sv)')
    ax1.set_title('Boundary-integrated transport time series')
    ax1.legend(fontsize=8)

    fig.tight_layout()
    os.makedirs(plot_dir, exist_ok=True)
    fpath = os.path.join(plot_dir, f'{reg_nm}_{bnd}_{vnm}_transport_check.png')
    fig.savefig(fpath, dpi=150)
    plt.close(fig)
    return fpath

############################################################
#                            MAIN                           #
############################################################

def main(config_dir, reg_nm, boundaries, itrs, do_correct, do_plot, output_dir,
         max_correction_speed, velocity_tolerance, verbose, legacy_bug_mode=False):
    grd_ls = ['XC', 'YC', 'AngleCS', 'AngleSN', 'HFacC', 'HFacS', 'HFacW', 'drF']
    obcs_dir = os.path.join(config_dir, 'forcings/OBCS/')

    if verbose:
        print('> Reading parent and downscaled grid geometry')
    tmp = read_eccogrid(config_dir, reg_nm)
    grid0 = dict(zip(grd_ls + ['rF'], tmp))
    Nr0 = tmp[grd_ls.index("HFacC")].shape[0]
    llc = tmp[grd_ls.index("XC")].shape[1]

    tmp = read_ncgrid(config_dir, reg_nm, grd_ls)
    ### Interior-face trim -- must stay identical to gen_obcs.py's, see the
    ### long comment there: [0] -> interior face of S/W, [-1] -> interior face
    ### of N/E, matching how MITgcm masks OBCS normal velocities.
    tmp[grd_ls.index("HFacS")] = tmp[grd_ls.index("HFacS")][:, 1:-1, :]
    tmp[grd_ls.index("HFacW")] = tmp[grd_ls.index("HFacW")][:, :, 1:-1]
    grid1 = dict(zip(grd_ls, tmp))
    Nr1 = tmp[grd_ls.index("HFacC")].shape[0]
    for nm in ['S', 'W']:
        m = np.copy(grid1["HFac" + nm]); m[m > 0] = 1
        grid1["mask" + nm] = m

    ### face lengths, needed on both the parent and downscaled side to turn
    ### velocity into transport; not part of gen_obcs.py's own grd_ls, but
    ### already present in the same source files it reads
    parent_grid_dir = os.path.join(config_dir, 'parent/outputs/grid/')
    grid0['dxG'] = transp_tiles(mds.rdmds(parent_grid_dir + 'DXG'))
    grid0['dyG'] = transp_tiles(mds.rdmds(parent_grid_dir + 'DYG'))
    tmp = read_ncgrid(config_dir, reg_nm, ['dxG', 'dyG'])
    ### dxG is (ny+1, nx) and dyG is (ny, nx+1): they live on the SAME
    ### staggered faces as HFacS/HFacW respectively, so they must get the SAME
    ### interior-face trim. Trimming them the other way round (dxG[:-1], as
    ### before) paired the interior-face mask with the outer-edge face length,
    ### so the transport integral mixed two different faces.
    grid1['dxG'] = tmp[0][1:-1, :]
    grid1['dyG'] = tmp[1][:, 1:-1]

    bnd_ls, dv_masks_ls = read_dv_masks(config_dir, boundaries, llc)
    bnd_domain = gen_bnd_domain(bnd_ls, dv_masks_ls, grid0, Nr0)
    ### gen_bnd_domain() only fills XC/YC/AngleCS/AngleSN/mask{C,S,W} for
    ### each boundary's native points; add dxG/dyG at those same points the
    ### same way, without touching gen_obcs.py itself
    _add_face_lengths_to_bnd_domain(bnd_domain, dv_masks_ls, bnd_ls, grid0)

    if do_correct:
        os.makedirs(output_dir, exist_ok=True)

    for bnd in bnd_ls:
        vnm = NORMAL_VNM[bnd]
        if bnd in ('east', 'west'):
            XC1 = grid1['XC'][:, -1:] if bnd == 'east' else grid1['XC'][:, :1]
            YC1 = grid1['YC'][:, -1:] if bnd == 'east' else grid1['YC'][:, :1]
            mask1 = grid1['maskW'][:, :, -1:] if bnd == 'east' else grid1['maskW'][:, :, :1]
            face1 = (grid1['dyG'][:, -1:] if bnd == 'east' else grid1['dyG'][:, :1]).ravel()
            coord1 = YC1.ravel()
        else:
            XC1 = grid1['XC'][-1:, :] if bnd == 'north' else grid1['XC'][:1, :]
            YC1 = grid1['YC'][-1:, :] if bnd == 'north' else grid1['YC'][:1, :]
            mask1 = grid1['maskS'][:, -1:, :] if bnd == 'north' else grid1['maskS'][:, :1, :]
            face1 = (grid1['dxG'][-1:, :] if bnd == 'north' else grid1['dxG'][:1, :]).ravel()
            coord1 = XC1.ravel()
        mask1_2d = mask1[:, :, 0] if bnd in ('east', 'west') else mask1[:, 0, :]
        n1 = mask1_2d.shape[1]

        if verbose:
            print(f'> [{bnd}] reading native parent velocity and downscaled {vnm}')
        native_vel = read_native_normal_velocity(config_dir, bnd, itrs, bnd_domain, Nr0, verbose=verbose,
                                                  legacy_bug_mode=legacy_bug_mode)
        child_vel = read_child_velocity(obcs_dir, bnd, vnm, Nr1, n1)
        print(f'    [{bnd}] {os.path.join(obcs_dir, f"{vnm}_{bnd}.bin")}: {child_vel.shape[0]} timestep(s)')
        if native_vel.shape[0] != child_vel.shape[0]:
            raise SystemExit(
                f"[{bnd}] timestep mismatch even after replicating gen_obcs.py's own file "
                f"discovery: native data has {native_vel.shape[0]} timestep(s), but "
                f"{os.path.join(obcs_dir, f'{vnm}_{bnd}.bin')} has {child_vel.shape[0]}. The "
                f"directory contents may have changed since gen_obcs.py was run (files added/"
                f"removed), which changes glob order. Pass the exact iteration(s) that were used "
                f"with multiple -i values to bypass auto-discovery entirely.")

        result = correct_boundary(bnd, bnd_domain, grid0, native_vel, coord1, face1,
                                   child_vel, mask1_2d, grid1['drF'],
                                   max_correction_speed=max_correction_speed,
                                   velocity_tolerance=velocity_tolerance)
        print_report(bnd, vnm, result)

        if do_plot:
            fpath = plot_boundary(bnd, vnm, reg_nm, result, os.path.join(output_dir or obcs_dir, 'diagnostics'))
            if verbose:
                print(f'    saved plot: {fpath}')

        if do_correct:
            out_path = os.path.join(output_dir, f'{vnm}_{bnd}.bin')
            result['corrected'].ravel('C').astype('>f4').tofile(out_path)
            if verbose:
                print(f'    wrote corrected file: {out_path}')

    if do_correct:
        ### copy every other boundary file (T/S/tracers/sea-ice/tangential
        ### velocity) through unchanged, so output_dir is a complete,
        ### ready-to-use set
        corrected_names = {f'{NORMAL_VNM[b]}_{b}.bin' for b in bnd_ls}
        for src in glob.glob(os.path.join(obcs_dir, '*.bin')):
            if os.path.basename(src) not in corrected_names:
                shutil.copy2(src, os.path.join(output_dir, os.path.basename(src)))
        if verbose:
            print(f'> copied remaining OBCS files (T/S/tracers/etc.) unchanged into {output_dir}')

############################################################
#                     SMALL LOCAL HELPERS                  #
############################################################

def _add_face_lengths_to_bnd_domain(bnd_domain, dv_masks_ls, bnd_ls, grid0):
    """gen_bnd_domain() only fills XC/YC/AngleCS/AngleSN/mask{C,S,W} for
    each boundary's native points; add dxG/dyG at those same points the
    same way, without touching gen_obcs.py."""
    for bnd, mask in zip(bnd_ls, dv_masks_ls):
        rows, cols = np.where(mask != 0)
        npts = len(bnd_domain[bnd]['XC'])
        dxG_pts = np.zeros(npts)
        dyG_pts = np.zeros(npts)
        for row, col in zip(rows, cols):
            idx = int(mask[row, col]) - 1
            dxG_pts[idx] = grid0['dxG'][row, col]
            dyG_pts[idx] = grid0['dyG'][row, col]
        bnd_domain[bnd]['dxG'] = dxG_pts
        bnd_domain[bnd]['dyG'] = dyG_pts

############################################################
#                          PARSER                           #
############################################################

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-d", "--config_dir", required=True, type=str,
                        help="Directory where gen_obcs.py's inputs/outputs live (same -d you gave it)")
    parser.add_argument("-n", "--reg_nm", required=True, type=str, help="Name of the regional cutout")
    parser.add_argument("-bnd", "--bnd_nm", required=True, type=str,
                        help="Open boundaries to check, e.g. ENS (only E/N/S/W with a normal-velocity "
                             "component are meaningful here)")
    parser.add_argument("-i", "--itr", nargs='+', type=int, required=True,
                        help="Same iteration(s) used when running gen_obcs.py")
    parser.add_argument("-correct", "--correct", action="store_true",
                        help="Write corrected UVEL/VVEL files (plus unchanged copies of everything "
                             "else) to --output_dir. Without this flag, only the mismatch report "
                             "(and plot, if -plot) is produced -- nothing is written.")
    parser.add_argument("-o", "--output_dir", type=str, default=None,
                        help="Where to write corrected files (default: <config_dir>/forcings/"
                             "OBCS_corrected/). Never overwrites gen_obcs.py's original output.")
    parser.add_argument("-plot", "--plot", action="store_true",
                        help="Save a transect + time-series diagnostic plot per boundary (requires matplotlib)")
    parser.add_argument("-maxcorr", "--max_correction_speed", type=float, default=2.0,
                        help="Safety cap (m/s) on the barotropic velocity correction added to any "
                             "single column (default 2.0)")
    parser.add_argument("-veltol", "--velocity_tolerance", type=float, default=0.2,
                        help="How far beyond the parent's own observed velocity range (as a fraction "
                             "of that range, default 0.2 = 20%%) the correction is allowed to push any "
                             "single depth level. Keeps corrected min/max velocities close to the "
                             "parent's, not just the net transport.")
    parser.add_argument("-legacy-bug-mode", "--legacy_bug_mode", action="store_true",
                        help="Replicate a known bug in the ORIGINAL gen_obcs.py (only the first+last "
                             "native diagnostics_vec file survive its merge loop when 3+ are present) "
                             "so this script's native-data reading matches what's actually in an "
                             "OBCS file generated by that unfixed script. Leave this off (default) "
                             "for files generated by gen_obcs2.py or any other fixed generator, "
                             "which correctly use every available file.")
    parser.add_argument("-v", "--verbose", action="store_true")

    args = parser.parse_args()
    output_dir = args.output_dir or os.path.join(args.config_dir, 'forcings/OBCS_corrected/')

    main(args.config_dir, args.reg_nm, args.bnd_nm, args.itr, args.correct, args.plot,
         output_dir, args.max_correction_speed, args.velocity_tolerance, args.verbose,
         args.legacy_bug_mode)

