#!/bin/csh
#PBS -l select=30:ncpus=20:model=sky_ele
#PBS -W group_list=g26113

#PBS -l walltime=120:00:00
#PBS -q long

##PBS -l walltime=2:00:00
##PBS -q debug

##PBS -j oe
#PBS -m abe

#PBS -N GoM
#PBS -o output
#PBS -e error
#PBS -l site=needed=/home3+/nobackupp27

module purge
module load comp-intel mpi-hpe hdf4 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 022
cd $PBS_O_WORKDIR
limit stacksize unlimited
setenv MPI_LAUNCH_TIMEOUT 40
mpiexec -np 600 ./mitgcmuv

