#!/bin/csh
#PBS -l select=1:ncpus=8:model=has
##PBS -l select=39:ncpus=20:model=ivy
##PBS -l walltime=120:00:00
##PBS -q long
#PBS -l walltime=2:00:00
#PBS -q debug
##PBS -q devel
#PBS -j oe
#PBS -m abe

#PBS -N v4_3deg_test
#PBS -o output
#PBS -e error

module purge
module load comp-intel/2016.2.181 mpi-sgi/mpt.2.14r19 hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

umask 022
cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 8 ./mitgcmuv
